# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
  en:
    contentDir: content/en
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Project Documentation
    params:
      descrption: English description
    weight: 1

# Uncomment the lines below to configure your website in a second language.
  ja:
    languageCode: ja
    contentDir: content/ja
    disabled: false
    languageDirection: ltr
    languageName: 日本語
    title: Japanese website title...
    params:
      description: Japanese description...
    weight: 2
