# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Reference, Tutorials, and Explanations
    title: Project Documentation
    weight: 1

# Uncomment the lines below to configure your website in a second language.
ja:
 languageCode: ja
 contentDir: content/ja
 disabled: false
 languageDirection: ltr
 title: Japanese website title...
 params:
   description: Japanese description...
 menu:
   main:
     - name: 役田歴真
       url: '#about'
       weight: 2
